version: '3'
services:

  stocking-stuffer-api:
    build: ./api
    container_name: stocking-stuffer-api
    environment:
      - PORT=3000
      - DB_CONNECTION=mongodb+srv://Ryan:Sportking11@vue-tut.iuu2u.mongodb.net/stocking-stuffers?retryWrites=true&w=majority
      - SESSION_SECRET=1a256cae-99dc-4a0b-80ee-98141f06d0da
      - CORS_ADDRESS=http://172.17.0.2:8080
    ports:
      - 3000:3000

  stocking-stuffer-ui:
    build: ./frontend
    container_name: stocking-stuffer-ui
    environment:
      - VUE_APP_LOCAL_API=stocking-stuffer-api
    links:
      - stocking-stuffer-api

volumes:
  stocking-stuffer-data