version: '3'
services:
  stocking-stuffer-api:
    container_name: stocking-stuffer-api
    restart: always
    build: ./api
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/stocking-stuffer-db
      - SESSION_SECRET=1a256cae-99dc-4a0b-80ee-98141f06d0da
    ports:
      - 3000:3000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  stocking-stuffer-ui:
    container_name: stocking-stuffer-ui
    build: ./frontend
    ports:
      - 8080:8080
    links:
      - stocking-stuffer-api
    environment:
      - VUE_APP_BACKEND_URL=http://stocking-stuffer-api:3000